add draft: guide for usdc bridge
conduitxyz/conduit-docs pull request #40
Opened 2024-09-21 13:45 UTC by siljapetasch

2024-09-24 08:19 UTC, emilianobonassi commented
op https://github.com/defi-wonderland/opUSDC
arb https://github.com/OffchainLabs/token-bridge-contracts/tree/main/scripts/usdc-bridge-deployment

op requires UI/partners info about new contracts
arb natively integrated

2024-09-24 08:26 UTC, emilianobonassi commented
op ok custom documentation and refer to opusdc for more info
for arb no need, just link https://docs.arbitrum.io/build-decentralized-apps/token-bridging/token-bridge-erc20

2024-09-24 17:52 UTC, siljapetasch commented
content is done, will double-check for typos in the morning

2024-09-25 08:15 UTC, tadad commented on pages/usdc_bridge/overview.mdx
> +- **Bridged USDC Token Address:** `TBD`
this they can find in the dashboard, it will vary from chain to chain

2024-09-25 10:02 UTC, tadad requested changes

2024-09-25 12:03 UTC, tadad approved these changes

2024-09-26 00:08 UTC, emilianobonassi commented
merging for now to have link available for comms

2024-09-26 00:08 UTC, merged